import type { Product, Scan, RetailerAnalytics } from "./types"

export const mockProducts: Product[] = [
  {
    id: "prod-001",
    name: "Wild Alaskan Salmon",
    species: "Sockeye Salmon (Oncorhynchus nerka)",
    image: "/fresh-wild-alaskan-salmon-fillet.jpg",
    qrCode: "FISH-AK-SAL-001",
    caughtDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    caughtLocation: "Bristol Bay, Alaska",
    fishingMethod: "Drift gillnet",
    vesselName: "Pacific Harvest",
    processedDate: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    processingFacility: "Alaska Seafood Processing Co.",
    retailer: "Ocean Fresh Market",
    shelfDate: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
    price: 24.99,
    weight: 1.2,
    sustainabilityRating: "excellent",
    isMSCCertified: true,
    quotaCompliant: true,
    mercuryLevel: "low",
    omega3Content: 2260,
    temperatureHistory: [
      {
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 2,
        location: "Vessel hold",
      },
      {
        timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 1,
        location: "Processing facility",
      },
      {
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 2,
        location: "Transport",
      },
      {
        timestamp: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 3,
        location: "Retail display",
      },
    ],
    carbonFootprint: 2.3,
  },
  {
    id: "prod-002",
    name: "Atlantic Cod",
    species: "Atlantic Cod (Gadus morhua)",
    image: "/fresh-atlantic-cod-fillet.jpg",
    qrCode: "FISH-AT-COD-002",
    caughtDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    caughtLocation: "North Sea, Norway",
    fishingMethod: "Bottom trawl",
    vesselName: "Nordic Star",
    processedDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    processingFacility: "Bergen Fish Processing",
    retailer: "Ocean Fresh Market",
    shelfDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    price: 16.99,
    weight: 0.8,
    sustainabilityRating: "fair",
    isMSCCertified: false,
    quotaCompliant: true,
    mercuryLevel: "low",
    omega3Content: 208,
    temperatureHistory: [
      {
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 1,
        location: "Vessel hold",
      },
      {
        timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 2,
        location: "Processing facility",
      },
      {
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 4,
        location: "Transport",
      },
      {
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 5,
        location: "Retail display",
      },
    ],
    carbonFootprint: 4.8,
  },
  {
    id: "prod-003",
    name: "Yellowfin Tuna",
    species: "Yellowfin Tuna (Thunnus albacares)",
    image: "/fresh-yellowfin-tuna-steak.jpg",
    qrCode: "FISH-YF-TUN-003",
    caughtDate: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    caughtLocation: "Pacific Ocean, Hawaii",
    fishingMethod: "Pole and line",
    vesselName: "Island Fisherman",
    processedDate: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
    processingFacility: "Hawaiian Seafood Co.",
    retailer: "Ocean Fresh Market",
    shelfDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    price: 32.99,
    weight: 0.6,
    sustainabilityRating: "good",
    isMSCCertified: true,
    quotaCompliant: true,
    mercuryLevel: "moderate",
    omega3Content: 108,
    temperatureHistory: [
      {
        timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: -1,
        location: "Vessel hold",
      },
      {
        timestamp: new Date(Date.now() - 2.5 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 0,
        location: "Processing facility",
      },
      {
        timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 1,
        location: "Transport",
      },
      {
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 2,
        location: "Retail display",
      },
    ],
    carbonFootprint: 3.1,
  },
  {
    id: "prod-004",
    name: "Farm-Raised Tilapia",
    species: "Nile Tilapia (Oreochromis niloticus)",
    image: "/fresh-tilapia-fillet.jpg",
    qrCode: "FISH-FR-TIL-004",
    caughtDate: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    caughtLocation: "Aquaculture Farm, Vietnam",
    fishingMethod: "Farm-raised",
    vesselName: "N/A",
    processedDate: new Date(Date.now() - 3.5 * 24 * 60 * 60 * 1000).toISOString(),
    processingFacility: "Mekong Processing Plant",
    retailer: "Ocean Fresh Market",
    shelfDate: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    price: 9.99,
    weight: 1.0,
    sustainabilityRating: "good",
    isMSCCertified: false,
    quotaCompliant: true,
    mercuryLevel: "low",
    omega3Content: 134,
    temperatureHistory: [
      {
        timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 3,
        location: "Farm facility",
      },
      {
        timestamp: new Date(Date.now() - 3.5 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 2,
        location: "Processing facility",
      },
      {
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 3,
        location: "Transport",
      },
      {
        timestamp: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 4,
        location: "Retail display",
      },
    ],
    carbonFootprint: 5.2,
  },
  {
    id: "prod-005",
    name: "Wild Pacific Halibut",
    species: "Pacific Halibut (Hippoglossus stenolepis)",
    image: "/fresh-pacific-halibut-steak.jpg",
    qrCode: "FISH-PC-HAL-005",
    caughtDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    caughtLocation: "Gulf of Alaska",
    fishingMethod: "Longline",
    vesselName: "Northern Pride",
    processedDate: new Date(Date.now() - 0.8 * 24 * 60 * 60 * 1000).toISOString(),
    processingFacility: "Alaska Seafood Processing Co.",
    retailer: "Ocean Fresh Market",
    shelfDate: new Date(Date.now() - 0.3 * 24 * 60 * 60 * 1000).toISOString(),
    price: 28.99,
    weight: 0.9,
    sustainabilityRating: "excellent",
    isMSCCertified: true,
    quotaCompliant: true,
    mercuryLevel: "moderate",
    omega3Content: 395,
    temperatureHistory: [
      {
        timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 1,
        location: "Vessel hold",
      },
      {
        timestamp: new Date(Date.now() - 0.8 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 0,
        location: "Processing facility",
      },
      {
        timestamp: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 1,
        location: "Transport",
      },
      {
        timestamp: new Date(Date.now() - 0.3 * 24 * 60 * 60 * 1000).toISOString(),
        temperature: 2,
        location: "Retail display",
      },
    ],
    carbonFootprint: 1.8,
  },
]

// Generate mock scans for analytics
export const mockScans: Scan[] = []
const now = Date.now()
for (let i = 0; i < 500; i++) {
  const daysAgo = Math.floor(Math.random() * 30)
  mockScans.push({
    id: `scan-${i}`,
    productId: mockProducts[Math.floor(Math.random() * mockProducts.length)].id,
    timestamp: new Date(now - daysAgo * 24 * 60 * 60 * 1000).toISOString(),
    location: "Ocean Fresh Market",
  })
}

export const mockRetailerAnalytics: RetailerAnalytics = {
  retailerId: "retailer-001",
  retailerName: "Ocean Fresh Market",
  totalScans: 1247,
  topProducts: [
    { productId: "prod-001", productName: "Wild Alaskan Salmon", scans: 342, avgScore: 92 },
    { productId: "prod-003", productName: "Yellowfin Tuna", scans: 289, avgScore: 85 },
    { productId: "prod-005", productName: "Wild Pacific Halibut", scans: 234, avgScore: 94 },
    { productId: "prod-004", productName: "Farm-Raised Tilapia", scans: 198, avgScore: 78 },
    { productId: "prod-002", productName: "Atlantic Cod", scans: 184, avgScore: 71 },
  ],
  scanTrend: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(now - (29 - i) * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
    scans: Math.floor(Math.random() * 50) + 20,
  })),
  sustainabilityPreference: {
    excellent: 45,
    good: 35,
    fair: 15,
    poor: 5,
  },
  avgFishScore: 84,
  wasteReduction: 23,
  revenueImpact: 45600,
}
